### ISSUE TITLE
how to track ar tag without camera frame

### ISSUE THREAD

**Issue by 130s** [ros-perception/ar_track_alvar#20]
_From @zfxw0206 on September 2, 2016 19:55_

Now I have a pointgrey camera which does not have camera frame. How cam I use ar track with this camera?

Thank you!

_Copied from original issue: sniekum/ar_track_alvar#89_

**Comment by 130s** [comment]
_From @mehditlili on September 12, 2016 12:17_

Just write anything in camera frame. The markers will be published with frame_id as what you set and if you want to see them in rviz just set your fixed frame to that same frame of the camera.

**Comment by 130s** [comment]
_From @zfxw0206 on November 3, 2016 14:55_

Thank you. I set the id in the calibration yaml file. Then it is fine.

**Comment by mehditlili** [comment]
I think this issue can be closed.
