### ISSUE TITLE
Is there a way to increase the frequency of pr2_indiv_no_kinect.launch?

### ISSUE THREAD

**Issue by vannem95** [ros-perception/ar_track_alvar#43]
I am using a logitech c920 to detect a marker. I am running pr2_indiv_no_kinect launch file. But the whole thing is only running at 1hz. In the node file, it says there is a parameter called max_frequency which is already set to 8.0 and I tried to set it to 30 but nothing changed. Anyone know how to get it to run faster?

**Comment by 130s** [comment]
You could get more response in ROS official QA forum http://answers.ros.org/ for the questions like this. Also if you find a way to change then pull request is always welcomed.

**Comment by vannem95** [comment]
Ok. I will post there as well.

**Comment by amitfishy** [comment]
Edit the launch file or put the parameter in the node init:
```
<param name="max_frequency"       type="double" value="10" />
```

**Comment by 130s** [comment]
Closing as this seems to have been asked [here](https://answers.ros.org/question/275598/ar_track_alvar-running-too-slow1hz/).

@amitfishy It'd be great if you could answer there.
