### ISSUE TITLE
Pose publication too slow

### ISSUE THREAD

**Issue by ziqi-zhang** [ros-perception/ar_track_alvar#47]
I use Ubuntu 16.04 and ros kinetic. My CPU is Intel I7 with 8G memory. When I use ar_track_alvar, it publish poses at poor 0.2hz. I believe there must be something wrong. Can anyone help me to figure it out?

I set all parameters of ar_track_alvar same as default parameters. It subscribe /camera/rgb/image_raw and /camera/rgb/camera_info. I didn't change any other thing.

Thanks!

**Comment by 130s** [comment]
For technical questions, asking on http://answers.ros.org/ might exposed to way more people (see only 7 persons are subscribing to this repo).

That said, I close this (but once you opened a question there, you might link there from here so that others can keep track). Thanks.
