### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by pcoenen** [ros-perception/ar_track_alvar#66]
Hello,

I guess this a ar_track_alvar repo for ros melodic?

Is there somebody that can explain me how to install this on ros melodic ? Or is there a manual somewhere ?

**Comment by alecGraves** [comment]
you can git clone the repository into your catkin workspace/src, and then you can build it with catkin make. 
e.g.
```bash
cd catkin_ws/src
git clone https://github.com/ros-perception/ar_track_alvar.git
cd ..
catkin_make
source devel/setup.bash
```
Then you should be able to use the package like normal.

**Comment by alecGraves** [comment]
On ubuntu, you may be able to install with the following:
```
sudo apt-get install ros-melodic-ar-track-alvar
```
